buildutils/torque.spec.in
As discussed on torquedev mailing list; this patch to the torque.spec allows building of Torque RPM's with a custom trqauthd-sock-dir.
It defines a variables to be specified via the command line:
rpmbuild -ba --define 'trqauthd_sock_dir /var/run' ./torque.spec
This in turn results in rpmbuild calling configure appropriately:
./configure --with-trqauthd-sock-dir=/var/run
If not defined it will default back to /tmp
=> Changed .spec-file to allow building RPMs with custom trqauthd-sock-dir

src/resmom/mom_main.c
The mom contains all the code to create a thread pool, and a configuration setting 
`$thread_unlink_calls true`
will queue the `delete_job_files` call in the pool. However, the pool was never started and the function never ran.
=> start the thread pool in the mom after creating it

src/resmom/mom_job_func.c
The remtree() function recursively deletes files and directories, and skips over `.` and `..`. However, the code that matches `..` also matches file and directory names starting with `..` since there is no check for a terminating `\0`. The modified expression is also simplified by eliminating all the unnecessary parentheses; logic expressions evaluate left-to-right.
=> remtree: don't skip files that start with two dots (exact match on '..')

src/cmds/qstat.c, src/scheduler.tcl/pbs_tclWrap.c
I found this to be necessary because I couldn't compile torque on ubuntu 14.04 because of these deprecated calls to the interp->results guy in tcl.
=> replaced deprecated calls to interp->result

contrib/init.d/pbs_server.in
Fixed an incompatibility in the init script with high availability setup.
qterm would cause the active (listening) server to shutdown, which could be a remote server instead of the local server as expected.
Reverting the code to pre-4.1.3 behavior: Sending SIGTERM to local pbs_server instance, this would orderly shut down server process, regardless of HA / single master configuration.
=> Fixed bug in high availability setup

src/cmds/qstat.c, src/include/log.h, src/lib/Liblog/pbs_log.c, src/resmom/linux/mom_mach.c, src/resmom/start_exec.c
This is a workaround for #324.
A real fix would be to avoid the reliance on btime, instead tracking jiffies.
- added logging to track found time differences
- allow for a time difference up to 1 hour (3600 seconds).
- make sure qstat does something when run without arguments (see #322)
=> Avoid killing running jobs due to time drift when the mom restarts 

src/include/pbs_nodes.h, src/lib/Libattr/test/attr_node_func/Makefile.am, src/lib/Libattr/test/attr_node_func/scaffolding.c, src/lib/Libutils/u_mutex_mgr.cpp, src/resmom/linux/numa_node.cpp, src/resmom/test/mom_job_func/scaffolding.c, src/resmom/test/start_exec/scaffolding.c, src/server/execution_slot_tracker.cpp, src/server/job_route.c, src/test/torque_test_lib/test_tcp_dis.cpp
I have cleaned up the code for a clean (no warnings) compilation on GCC 5.1.1
There are still some issues with the tests. The compilation isn't deterministic. Linking seems to fail intermittently (entering the affected directory and doing `make clean && make check` seems to fix it).
=> Code cleanup for clean compilation

contrib/systemd/pbs_mom.service.in
The code had a fixed directory which can differ from PBS_HOME as used in the deployment.
=> Replace the fixed home dir with the PBS_HOME variable

README.building_40, configure.ac, src/daemon_client/Makefile.am
My desktop was reinstalled with RHEL 7 and I came across this dependency.  If someone wants to actually use openssl functions, this can be reverted.  Closes #219
=> Remove unnecessary dependency on openssl-devel

doc/man7/pbs_server_attributes.7.in
This adds several missing server attributes.  Text was
copied from the Adaptive Computing TORQUE documentation.
Work remains to ensure all parameters are documented.
=> Update pbs_server_attributes(7) man page

buildutils/torque.spec.in
see https://github.com/adaptivecomputing/torque/pull/335#issuecomment-155190481
=> User created rpm macros should not start with _

src/lib/Libnet/net_client.c
When the pbs_mom cannot connect to the qsub process, log the destination
port, not the source port that has already been bound.
=> (#329) Fix error message for failed interactive connection

src/test/attr_node_func/test_uut.c
This test seems to be testing UTC parsing, but is using local time for the test. The test will not pass using localtime with central european time zone.
=> Modify UTC parsing test to actually take UTC time.

src/cmds/pbsnodes.c, src/cmds/pbsnodes.h
This issue was discovered by troubleshooting a problem where occasionally some nodes were marked offline without a note by nhc. Trying to determine the root cause I noticed in the logs of nhc, the following pbsnodes output: "Error marking node nodename......" that occurred when nodes were found offline without a note.  The way pbsnodes currently works (when given -c -N) is it calls set_note first and then marknode, which both call pbs_manager_err.  The bug happens when nhc runs "pbsnodes -c -N '' nodename" and pbs_manager_err succeeds for set_note and fails for marknode, this clears the note but does not put the node back online.  The fix is for pbsnodes to set the note and node state with a single pbs_manager_err call, which means both change atomically.  nhc works by marking a node …
=> pbsnodes does not change the note and node state (offline,online) atomically

src/resmom/linux/cpuset.c
Most errors won't show up until you close the file.
=> Check return code when moving tasks into a cpuset

doc/man7/pbs_server_attributes.7.in
The default value for down_on_error was changed in https://github.com/adaptivecomputing/torque/commit/f33c05a014d5f0d9e1b7b7226f0ce0e02f1e79a9#diff-f41edbf0d83389af469d191a7aa5b195. This change updates the documentation to reflect that change.
On another note, is this still an experimental feature as the man page says?
=> Mistake in the man page. down_on_error is currently true by default now.

buildutils/torque.spec.in, src/include/trq_cgroups.h, src/resmom/mom_comm.c
only creating the torque sub-cgroup during pbs_mom startup is not-sufficient. at least for memory and devices, it seems that systemd removes the sub-cgroup when no tasks are in it 
to reproduce 
```
[root@node2804 ~]# rpm -q systemd
systemd-219-19.el7_2.7.x86_64
[root@node2804 ~]# ls /sys/fs/cgroup/memory/woohoo | wc -l
ls: cannot access /sys/fs/cgroup/memory/woohoo: No such file or directory
0
[root@node2804 ~]# mkdir /sys/fs/cgroup/memory/woohoo
[root@node2804 ~]# ls /sys/fs/cgroup/memory/woohoo | wc -l
31
[root@node2804 ~]# systemctl daemon-reload
[root@node2804 ~]# systemctl restart autofs
[root@node2804 ~]# ls /sys/fs/cgroup/memory/woohoo | wc -l
ls: cannot access /sys/fs/cgroup/memory/woohoo: No such file or directory
0
```
(which service you restart is not relevant)
seems related …
=> re-initialize the torque cgroup subdirectories due to systemd cleanup of empty/unused cgroups

src/server/req_runjob.c, src/server/svr_jobfunc.c
Started taking 4.2.10 into production, and immediately ran into trouble. For some reason every now and again there is a miscommunication between the server and the mom which causes a failure to start a job. This happens after the files are already staged in. Due to the handling of the situation, a later attempt to rerun the job crashes the server.
The two commits make sure that the job is cleared of the stagedIn flag so it can be rerun, and guard against the unsafe assumption that exec_host will be set if the StagedIn flag is set.
=> 4.2 dev fixcrash

src/server/svr_movejob.c
All starting jobs produce a line in the log file like
child reported success for job after 1 seconds (dest=???), rc=0
The three question marks are due to `node_name` not being set. This small patch sets the node_name from the destination.
=> set node_name for logging the destination worker node instead of '???'

src/resmom/generate_alps_status.c
On a new system we left $apbasil_protocol unset and the reporter mom segfaults.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5952b5a in __strcmp_sse2_unaligned () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install libgcc_s1-debuginfo-5.2.1+r226025-4.1.x86_64 liblzma5-debuginfo-5.0.5-4.852.x86_64 libopenssl1_0_0-debuginfo-1.0.1i-27.6.1.x86_64 libstdc++6-debuginfo-5.2.1+r226025-4.1.x86_64 libxml2-2-debuginfo-2.9.1-17.1.x86_64 libz1-debuginfo-1.2.8-5.1.x86_64
(gdb) bt
#0  0x00007ffff5952b5a in __strcmp_sse2_unaligned () from /lib64/libc.so.6
#1  0x000000000047d212 in generate_alps_status (status=..., apbasil_path=0x11b5cc0 "/opt/cray/alps/default/bin/apbasil", apbasil_protocol=0x0)
at generate_alps_status.c:1056
#2  0x000000000044c06b in …
```
=> Fix a crash in the ALPS reporter mom if apbasil_protocol is unset

configure.ac
Allow us to point to a specific PMIx installation. Install the version detection logic so we know precisely which version of PMIx we are building against.
=> Modify the PMIx support configure logic to use --with-pmix

contrib/systemd/pbs_server.service.in
RemainAfterExit will keep the unit active even if no processes are running anymore (instead of failed).
From the man-page:
```
RemainAfterExit=
Takes a boolean value that specifies whether the service shall be considered active even when all its processes exited. Defaults to no.
```
=> drop remainafterexit in pbs_server unit file

buildutils/torque.spec.in
If no other ldflag is definied, use the LDFLAGS value passed on to the
configure script.
=> Add macro for LDFLAGS (like for CFLAGS)

Makefile.am
Now you can do things like: `make RPMOPTS='--define "_topdir /my/top/dir"'`. 
Please also cherry pick to 6.0-dev.
=> Also let user specify rpmbuild options to source build

configure.ac
Currently, pkg-config is used to find hwloc >= 1.9 but the result is
then ignored to check the hwloc library. This will cause it to fail if
there is a newer hwloc on a non-standard location.
=> Do not recheck the result of pkg-config

src/daemon_client/Makefile.am, src/resmom/Makefile.am
There is no point in running it when you're not root (like when building rpms).
=> Only execute ldconfig when run as root

contrib/pbstop
The pbstop contrib tool parses the output of 'qmgr -l -n' and
uses the information to display a grid of the cluster which shows
where jobs are running.
It seems that starting with commit 1573753 the format of the job
list returned by pbsnodes/qmgr changed so that multiple core jobs
was condensed and this borke the pbstop parsing algorithm. This is
a simple patch that will recognize the new format.
The format for the "jobs" attribute of a node was:
0/JOB1, 1/JOB1, 2/JOB1, 3/JOB2
Now it is:
0-2/JOB1, 3/JOB2
I wasn't able to test the modPBS routine but the format should be the same.
=> Let pbstop parser read consecutive index jobs

configure.ac
The --[en|dis]able-spool parameter was not passed to the rpmbuild phase,
which meant the spool setting was not altered when making the rpm. This
patch solves this issue.
=> Support the spool option when making rpm

src/resmom/accelerators_numa.cpp
NVML returns `00000000` as PCI domain while sysfs uses `0000`. This patch trims the 8 zeros to 4 to read from sysfs.
For example, on our system NVML returned: `00000000:82:00.0` while the sysfs path was `0000:82:00.0`.
I'm not entirely sure if this is the right approach. Maybe first try to read the full path and only then fall back to the one with the trimmed zeros?
Please backport to 6.1.2.
=> Trim down on zeros in PCI domain for sysfs
